In [100]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib

In [101]:
df = pd.read_csv("forecast_df.csv")

In [102]:
df.head(15)

    year  month              state       disease_name  total_cases
0   2018      1     Andhra Pradesh   Anxiety Disorder            2
1   2018      1     Andhra Pradesh             Asthma            1
2   2018      1     Andhra Pradesh           COVID-19            1
3   2018      1     Andhra Pradesh         Depression            1
4   2018      1     Andhra Pradesh  Diabetes (Type 2)            1
5   2018      1     Andhra Pradesh           HIV/AIDS            1
6   2018      1     Andhra Pradesh       Hypertension            2
7   2018      1     Andhra Pradesh        Oral Cancer            1
8   2018      1     Andhra Pradesh             Stroke            1
9   2018      1  Arunachal Pradesh             Asthma            1
10  2018      1              Assam               COPD            1
11  2018      1              Assam           Diarrhea            1
12  2018      1              Assam           HIV/AIDS            1
13  2018      1              Assam          Pneumonia            2
14  2018      1              Bihar             Asthma            2

In [103]:
df.shape

(15853, 5)

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15853 entries, 0 to 15852
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          15853 non-null  int64
 1   month         15853 non-null  int64
 2   state         15853 non-null  object
 3   disease_name  15853 non-null  object
 4   total_cases   15853 non-null  int64
dtypes: int64(3), object(2)
memory usage: 619.4+ KB

In [105]:
df.describe()

               year         month   total_cases
count  15853.000000  15853.000000  15853.000000
mean    2021.505709      6.671419      1.261591
std        2.295273      3.481879      0.585605
min     2018.000000      1.000000      1.000000
25%     2020.000000      4.000000      1.000000
50%     2022.000000      7.000000      1.000000
75%     2024.000000     10.000000      1.000000
max     2025.000000     12.000000      6.000000

In [106]:
df.isnull().sum()

year            0
month           0
state           0
disease_name    0
total_cases     0
dtype: int64

In [107]:
df.duplicated().sum()

np.int64(0)

In [108]:
df.columns

Index(['year', 'month', 'state', 'disease_name', 'total_cases'], dtype='object')

In [109]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

columns = [
    "state",
    "disease_name"
]

for col in columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

In [110]:
print(df.columns)

Index(['year', 'month', 'state', 'disease_name', 'total_cases'], dtype='object')

In [111]:
for col, encoder in label_encoders.items():
    print(f"\n{col}")
    mapping = dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))
    print(mapping)

state
{'Andaman and Nicobar Islands': np.int64(0), 'Andhra Pradesh': np.int64(1), 'Arunachal Pradesh': np.int64(2), 'Assam': np.int64(3), 'Bihar': np.int64(4), 'Chandigarh': np.int64(5), 'Chhattisgarh': np.int64(6), 'Goa': np.int64(7), 'Gujarat': np.int64(8), 'Haryana': np.int64(9), 'Himachal Pradesh': np.int64(10), 'Jammu and Kashmir': np.int64(11), 'Jharkhand': np.int64(12), 'Karnataka': np.int64(13), 'Kerala': np.int64(14), 'Madhya Pradesh': np.int64(15), 'Maharashtra': np.int64(16), 'Manipur': np.int64(17), 'Meghalaya': np.int64(18), 'Mizoram': np.int64(19), 'NCT of Delhi': np.int64(20), 'Nagaland': np.int64(21), 'Odisha': np.int64(22), 'Puducherry': np.int64(23), 'Punjab': np.int64(24), 'Rajasthan': np.int64(25), 'Sikkim': np.int64(26), 'Tamil Nadu': np.int64(27), 'Telangana': np.int64(28), 'Tripura': np.int64(29), 'Uttar Pradesh': np.int64(30), 'Uttarakhand': np.int64(31), 'West Bengal': np.int64(32)}

disease_name
{'Anxiety Disorder': np.int64(0), 'Asthma': np.int64(1), 'Breast Cancer': np.int64(2), 'COPD': np.int64(3), 'COVID-19': np.int64(4), 'Chikungunya': np.int64(5), 'Cholera': np.int64(6), 'Chronic Kidney Disease': np.int64(7), 'Dengue': np.int64(8), 'Depression': np.int64(9), 'Diabetes (Type 2)': np.int64(10), 'Diarrhea': np.int64(11), 'Filariasis': np.int64(12), 'Gastroenteritis': np.int64(13), 'HIV/AIDS': np.int64(14), 'Heart Disease': np.int64(15), 'Hepatitis B': np.int64(16), 'Hypertension': np.int64(17), 'Japanese Encephalitis': np.int64(18), 'Jaundice (Hepatitis A)': np.int64(19), 'Kala-Azar': np.int64(20), 'Leptospirosis': np.int64(21), 'Lung Cancer': np.int64(22), 'Malaria': np.int64(23), 'Oral Cancer': np.int64(24), 'Pneumonia': np.int64(25), 'Sickle Cell Anemia': np.int64(26), 'Stroke': np.int64(27), 'Swine Flu (H1N1)': np.int64(28), 'Thalassemia': np.int64(29), 'Tuberculosis': np.int64(30), 'Typhoid': np.int64(31)}

In [112]:
df.head()

   year  month  state  disease_name  total_cases
0  2018      1      1             0            2
1  2018      1      1             1            1
2  2018      1      1             4            1
3  2018      1      1             9            1
4  2018      1      1            10            1

In [113]:
X = df[['year', 'month', 'state', 'disease_name']]

y = df["total_cases"]

In [114]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [115]:
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [116]:
pred = model.predict(X_test)

pred[:10]

array([1.08, 1.27, 1.16, 1.08, 1.43, 1.28, 1.04, 1.19, 1.18, 1.  ])

In [117]:
print("MAE:", mean_absolute_error(y_test, pred))

print("RMSE:", np.sqrt(mean_squared_error(y_test, pred)))

print("R2 Score:", r2_score(y_test, pred))

MAE: 0.39315988647114475
RMSE: 0.5937803088581146
R2 Score: -0.03859857368099129

In [118]:
state = label_encoders["state"].transform(["Maharashtra"])[0]
disease = label_encoders["disease_name"].transform(["Dengue"])[0]

future = pd.DataFrame({
    "year": [2026],
    "month": [8],
    "state": [state],
    "disease_name": [disease]
})

prediction = model.predict(future)

print("Predicted Cases:", round(prediction[0]))

Predicted Cases: 2

In [120]:
import os
print(os.getcwd())

/Users/shrushtikurve